// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "HYInteractableActor.h"
#include "HYManualPickUp.generated.h"

/**
 * 
 */
UCLASS()
class HWANYOUNG2_API AHYManualPickUp : public AHYInteractableActor
{
	GENERATED_BODY()
public:
	AHYManualPickUp();

	void Interact_Implementation(APlayerController* Controller) override;

protected:
	UPROPERTY(EditAnywhere)
	UStaticMeshComponent* PickUpRangeMesh;

	UPROPERTY(EditAnywhere,BlueprintReadWrite)
	FName ItemID;
};
